version: '3.9'
services:
  hello-service:
    container_name: hello-service
    build: ./hello-service/
    ports:
      - "9081:8081"
    environment:
      STATUS_SERVICE_HOST: status-service
      STATUS_SERVICE_PORT: 8082

  status-service:
    container_name: status-service
    build: ./status-service/
    ports:
      - "9082:8082"
